{% set version = '0.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-biovis-reportr
  version: {{ version|replace("-", "_") }}

source:
  - path: ../

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, testthat
requirements:
  build:
    - r-base >=3.5
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - r-ggplot2

  run:
    - r-base
    - r-ggplot2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('BioVisReportR')"           # [not win]
    - "\"%R%\" -e \"library('BioVisReportR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/go-choppy/BioVisReportR
  license: AGPL 3.0 + file LICENSE
  summary: A R SDK for Choppy Report System. It contains color, input, config module. Color module
    is used to provide color palettes. Input module is used to handle input data. Config
    module is used to handle config file.
  license_family: AGPL
  license_file:
    - LICENSE

# The original CRAN metadata for this package was:

# Package: BioVisReportR
# Type: Package
# Title: A R SDK for Choppy Report System.
# Description: A R SDK for Choppy Report System. It contains color, input, config module. Color module is used to provide color palettes. Input module is used to handle input data. Config module is used to handle config file.
# Version: 0.1.0
# Date: 2019-06-09
# Authors@R: person("Jingcheng", "Yang", role=c("aut", "cre"), email="yjcyxky@163.com")
# Author: Jingcheng Yang [aut, cre]
# Maintainer: Jingcheng Yang <yjcyxky@163.com>
# URL: https://github.com/go-choppy/BioVisReportR
# BugReports: https://github.com/go-choppy/BioVisReportR/issues
# License: AGPL 3.0 + file LICENSE
# Depends: R (>= 3.0.0)
# Imports:
# Suggests: covr, testthat
# RoxygenNote: 6.1.0
# Roxygen: list(markdown = TRUE)

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
