name: release-package
on:
  push:
    tags:
      - v*
    branches:
      - master    

jobs:
  release-package:
    name: Run (${{ matrix.r-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        r-version: ["3.5", "3.6", "4.0", "4.1"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          auto-update-conda: true
      - name: Install conda-build
        shell: bash -l {0}
        # Error: expected str, bytes or os.PathLike object, not list
        # More details on https://github.com/conda/conda-build/issues/4222
        run: mamba install conda-build anaconda-client
      - name: Package & Release
        shell: bash -l {0}
        run: mamba build --R ${{ matrix.r-version }} conda.recipe --token ${{ secrets.ANACONDA_TOKEN }} --user biovis-report --skip-existing --output-folder build
